
export const metadata = {
  title: "Home | Project",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return <>
    <header>
      {/* nav bar */}

    </header>
    <main className="">
      {children}
    </main>
    {/* footer */}
  </>;
}
