
export const metadata = {
  title: "Home | Project",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return <>
    <main className="pt-16">
      {children}
    </main>
  </>;
}
