import React from 'react';
import EventComponent from './EventComponent';

export const metadata = {
  title: "Event Page",
  description: "Generated by create next app",
};

const EventsPage = () => {
    return (
        <div className='pt-14'>
            <EventComponent/>
        </div>
    );
};

export default EventsPage;