import React from 'react';
import EventComponent from './EventComponent';

export const metadata = {
  title: "Event Page",
  description: "Generated by create next app",
};

const EventsPage = () => {
    return (
        <div className='py-72'>
           <h2 className='text-7xl text-center'>Coming Soon.....</h2>
           {/* <EventComponent/> */}
        </div>
    );
};

export default EventsPage;