import React from 'react';

export const metadata = {
  title: "Sign Up page",
  description: "Generated by create next app",
};

const SignUpPage = () => {
    return (
        <div>
            SIGNUP
        </div>
    );
};

export default SignUpPage;