
import Footer from "@/app/(main)/components/footer/Footer";
import Navbar from "@/app/(main)/components/Navbar/Navbar";
import SignupFrom from "./componants/SignUpForm";


export const metadata = {
  title: "Sign Up page",
  description: "Generated by create next app",
};

export default function SignUpPage() {
  return (
    <div>
      <Navbar />
      <SignupFrom />
      <Footer />
    </div>
  );
}