import React from 'react';
import AboutUsSection from './AboutUsSection';

export const metadata = {
  title: "About us page",
  description: "Generated by create next app",
};

const AboutPage = () => {
    return (
        <div className='pt-14'>
            <AboutUsSection/>
        </div>
    );
};

export default AboutPage;