import React from 'react';

export const metadata = {
  title: "Sign in page",
  description: "Generated by create next app",
};

const SignInPage = () => {
    return (
        <div>
            sign in
        </div>
    );
};

export default SignInPage;