import React from 'react';
import SignInUser from './componants/SignInUser';

export const metadata = {
  title: "Sign In page",
  description: "Generated by create next app",
};

const SignInPage = () => {
  return (
    <div>
      <SignInUser/>
    </div>
  );
};

export default SignInPage;